routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'TodosController@index');

Route::resource('todo', 'TodosController');

app/Todo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    protected $fillable = [
        'title',
        'body',
        'date'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TodosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTodoRequest;
use App\Todo;
use Illuminate\Http\Request;
use SebastianBergmann\CodeCoverage\Report\Xml\Project;

class TodosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $todos = Todo::orderBy('created_at', 'desc')->get();
        return view('todos.index', compact('todos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('todos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTodoRequest $request)
    {
        $todo = Todo::create($request->all());
        $request->session()->flash('alert-success', 'Todo is successfully created!');
        return redirect(route('todo.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Todo $todo)
    {
        return view('todos.show', compact('todo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Todo $todo)
    {
        return view('todos.edit', compact('todo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateTodoRequest $request, Todo $todo)
    {
        $todo->update($request->all());
        $request->session()->flash('alert-info', 'Todo updated successfully');
        return redirect(route('todo.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Todo $todo)
    {
        $todo->delete();
        return redirect(route('todo.index'));
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href={{asset('css/app.css')}}>
        <title>Todolist</title>
    </head>

    <body>
        @include('layouts.inc.navbar')
        <div class="container my-3">
            @include('layouts.inc.alert')
            @yield('content')
        </div>

        <script src="{{ asset('js/bootstrap.js') }}"></script>
    </body>

</html>

resources/views/layouts/inc/alert.blade.php
@if($errors->any())
@foreach ($errors->all() as $error)
<section class="alert alert-danger">
    {{ $error }}
</section>
@endforeach
@endif

<section class="flash-message">
    @foreach (['danger', 'success', 'warning', 'info'] as $msg)
    @if (Session::has('alert-' . $msg))
    <section class="alert alert-{{ $msg }}">
        {{ Session::get('alert-' . $msg) }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </section>
    @endif
    @endforeach
</section>

resources/views/layouts/inc/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">TODO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ Request::is('/') ? 'active' : '' }}">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item {{ Request::is('todo/create') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('todo.create') }}">Create new todo</a>
            </li>
        </ul>
    </div>
</nav>

resources/views/todos/_form.blade.php
{!! Form::token() !!}
<section class="form-group">
    {!! Form::label('title', 'Title') !!}
    {!! Form::text('title', (isset($todo) ? $todo->title : null), ['class' => 'form-control']) !!}
</section>
<section class="form-group">
    {!! Form::label('body', 'Body') !!}
    {!! Form::textarea('body', (isset($todo) ? $todo->body : null), ['class' => 'form-control']) !!}
</section>
<section class="form-group">
    {!! Form::label('date', 'Date') !!}
    {!! Form::date('date', (isset($todo) ? $todo->date : null), ['class' => 'form-control']) !!}
</section>
{!! Form::submit((isset($todo) ? 'Save' : 'Create') , ['class' => 'btn btn-primary']) !!}
<a href="{{ route('todo.index') }}" class="btn btn-dark">Cancel</a>
{!! Form::close() !!}

resources/views/todos/create.blade.php
@extends('layouts.app')

@section('content')
<h1>Create New Todo:</h1>
{!! Form::open(['action' => 'TodosController@store']) !!}
@include('todos._form')
@endsection

resources/views/todos/edit.blade.php
@extends('layouts.app')

@section('content')
<h1>Update Todo</h1>
{!! Form::open(['action' => ['TodosController@update', $todo->id], 'method' => 'put']) !!}
@include('todos._form')
@endsection

resources/views/todos/index.blade.php
@extends('layouts.app')

@section('content')
<table class="table table-dark">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @if(count($todos) > 0)
        @foreach ($todos as $todo)
        <tr>
            <td>{{$todo->id}}</td>
            <td>{{$todo->title}}</td>
            <td>{{$todo->date}}</td>
            <td>
                <a href="{{ route('todo.show', $todo) }}" class="btn btn-primary">Show</a>
                <a href="{{ route('todo.edit', $todo) }}" class="btn btn-success">Edit</a>
                {!! Form::open(['action' => ['TodosController@destroy', $todo], 'method' => 'delete', 'class' =>
                'd-inline']) !!}
                {!! Form::submit('Delete' , ['class' => 'btn btn-danger']) !!}
                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
        @endif
        @endsection
    </tbody>
</table>

resources/views/todos/show.blade.php
@extends('layouts.app');

@section('content')
<section class="card">
    <section class="card-body">
        <h1>{{ $todo->title }}</h1>
        <p>{{ $todo->body }}</p>
    </section>
</section>
@endsection